author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Filter-CSV
no_index: 
  directory: 
    - inc
    - t
requires: 
  POE: 0.38
  Text::CSV: 0
version: 1.04
