author: 'Chris Williams <chris@bingosnet.co.uk>'
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
module_name: POE::Filter::CSV
name: POE-Filter-CSV
no_index:
  directory:
    - inc
    - t
requires:
  POE: 0.0607
  Text::CSV: 0
version: 1.03
