---
abstract: 'A POE-based parser for CSV based files.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-CSV
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Filter::CSV:
    file: lib/POE/Filter/CSV.pm
    version: 1.16
requires:
  POE: 0.38
  POE::Filter: 0
  Text::CSV: 1
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-filter-csv/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-filter-csv.git
version: 1.16
